dist: trusty
language: bash

python:
  - "3.6"
install:
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install python3.6
  - sudo apt-get -y install python3-setuptools
  - sudo easy_install3 pip
  - sudo pip3 install -r requirements.txt
script:
  - python --version
  - cd $TRAVIS_BUILD_DIR/tests; bash run_tests.sh
  - /usr/bin/python3 -m pyflakes

after_success:
- bash < (curl -s https://codecov.io/bash)
