dist: trusty
language: bash

python:
  - "3.6"
install:
  - sudo apt-get -y install python3-setuptools
  - sudo easy_install3 pip
  - pip3 install -r requirements.txt
script:
  - cd $TRAVIS_BUILD_DIR/tests; bash run_tests.sh
